server:
  port: 8000
  servlet:
    context-path: /api

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/marketplace
    username: root
    password: cosmin99
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true


  flyway:
    locations:
      - "classpath:db/migration"
#
##sendgrid confirmation
#  sendgrid:
#    api-key: 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