server:
  port: 8000
  servlet:
    context-path: /api

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/marketplace
    username: root
    password: 910604
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true


  flyway:
    locations:
      - "classpath:db/migration"
